import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Category, Report } from './types';
import { categoryColors, Empty, ErrorBoundary } from './components';
import { cents, peso } from './money';
export function TrendChart({ report }: { report: Report }) {
  const data = report.trends.map(t => ({ month: new Date(`${t.month}-01T12:00:00`).toLocaleDateString('en-PH', { month: 'short' }), income: cents(t.income) / 100, expense: cents(t.expense) / 100 }));
  if (!data.some(d => d.income || d.expense)) return <Empty title="Your month, at a glance" text="Your income and expenses will appear here as you add transactions." />;
  return <ErrorBoundary><div className="chart" role="img" aria-label={`Six month income and expense chart. Selected month income ${peso(report.income)}, expenses ${peso(report.expense)}.`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} barGap={6} margin={{ top: 10, right: 4, left: -18, bottom: 0 }}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#dce2ec" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#68758b', fontSize: 13 }} dy={8} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#68758b', fontSize: 12 }} tickFormatter={v => v >= 1000 ? `₱${v / 1000}k` : `₱${v}`} /><Tooltip cursor={{ fill: '#e7ecf580' }} contentStyle={{ borderRadius: 16, border: '1px solid #fff', background: '#f8faff', boxShadow: '0 8px 30px #26355212' }} formatter={(v, name) => [peso(Math.round(Number(v) * 100)), name === 'income' ? 'Income' : 'Expenses']} /><Bar dataKey="income" fill="#9eb1f9" radius={[5, 5, 0, 0]} maxBarSize={22} /><Bar dataKey="expense" fill="#4164ed" radius={[5, 5, 0, 0]} maxBarSize={22} /></BarChart></ResponsiveContainer></div></ErrorBoundary>;
}
export function CategoryChart({ breakdown, categories }: { breakdown: { category_id: string; amount: string }[]; categories: Category[] }) {
  const total = breakdown.reduce((sum, c) => sum + cents(c.amount), 0);
  const data = breakdown.map(c => { const name = categories.find(x => x.id === c.category_id)?.name ?? 'Other'; return { name, value: cents(c.amount), color: categoryColors[name] ?? '#8791a7' }; }).sort((a, b) => b.value - a.value);
  if (!total) return <Empty title="Where your money goes" text="Add an expense to see your category breakdown." />;
  return <ErrorBoundary><div className="category-chart"><div className="donut-wrap"><div className="donut" role="img" aria-label={`Category spending total ${peso(total)}`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" innerRadius="72%" outerRadius="94%" paddingAngle={4} cornerRadius={5} stroke="none">{data.map(d => <Cell key={d.name} fill={d.color} />)}</Pie><Tooltip formatter={v => peso(Number(v))} contentStyle={{ borderRadius: 14, border: 'none' }} /></PieChart></ResponsiveContainer></div><div className="donut-label"><span>Total spent</span><strong>{peso(total)}</strong></div></div><div className="legend-list">{data.map(d => <div key={d.name}><span className="legend-name"><i style={{ background: d.color }} />{d.name}</span><strong>{Math.round(d.value / total * 100)}%</strong></div>)}</div></div></ErrorBoundary>;
}
